# this file is responsible for automation basically, once the changes are commited, it performs the building and then the changes are deployed through the azure pipeline - this file is responsible for CI-CD
name: Angular CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.1

      - name: Install dependencies
        run: npm install

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          # THIS IS THE PART WHERE WE LOGIN TO THE AZURE REGISTRY - THESE ARE EXTERNALLY SET VARIABLES THAT ONLY EXIST IN THE GITHUB ACTIONS
          login-server: server3ac.azurecr.io
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Build Angular app for production
        run: npm run build -- --configuration=production
        # THE PART BELOW INCLUDES THE BUILDING OF THE DOCKER IMAGE AND ALSO PUSHING THAT IMAGE TO THE DOCKER CONTAINER IN THE AZURE APP SERVICE CONTAINERS

      - name: Build Docker image
        run: |
          docker build -t server3ac.azurecr.io/3ac-webapp-git-actions:latest .
          docker push server3ac.azurecr.io/3ac-webapp-git-actions:latest


        
